### ISSUE TITLE
Bug: Class m160209_074651_add_indexes_for_aggregate_rating_table does not exist

### ISSUE THREAD

**Issue by dignityinside** [Chiliec/yii2-vote#35]
When i try do "php yii migrate/down" i get this error:

```
Exception 'ReflectionException' with message 'Class m160209_074651_add_indexes_for_aggregate_rating_table does not exist'

in /home/dignity/vendor/yiisoft/yii2/di/Container.php:428

Stack trace:
#0 /home/dignity/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('m160209_074651_...')
#1 /home/dignity/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('m160209_074651_...')
#2 /home/dignity/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('m160209_074651_...', Array, Array)
#3 /home/dignity/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('m160209_074651_...', Array, Array)
#4 /home/dignity/vendor/yiisoft/yii2/console/controllers/MigrateController.php(201): yii\BaseYii::createObject(Array)
#5 /home/dignity/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(752): yii\console\controllers\MigrateController->createMigration('m160209_074651_...')
#6 /home/dignity/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(261): yii\console\controllers\BaseMigrateController->migrateDown('m160209_074651_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionDown(1)
#8 /home/dignity/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/dignity/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/dignity/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('down', Array)
#11 /home/dignity/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('down', Array)
#12 /home/dignity/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/down', Array)
#13 /home/dignity/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/down', Array)
#14 /home/dignity/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /home/dignity/yii(16): yii\base\Application->run()
#16 {main}

```

**Comment by chiliec** [comment]
You need to do `migrate/down` in same way as `migrate/up`, with:
 ```php
--migrationPath=@vendor/chiliec/yii2-vote/migrations
```

**Comment by chiliec** [comment]
If you know how to include this path in app config on a par with the default path, please let me know :)

**Comment by dignityinside** [comment]
Cool, thank you.
